SUBNET_MASK = 1
ROUTER = 3
TIME_SERVER = 4
NAME_SERVER = 5
DOMAIN_NAME_SERVER = 6
DOMAIN_NAME = 15

DHCP_REQ_IP = 50
DHCP_LEASE_TIME = 51
DHCP_MSG_TYPE = 53
DHCP_SERV_ID = 54
DHCP_PARAM_REQ = 55

END = 255